### ISSUE TITLE
RenderDoc update to 1.17?

### ISSUE THREAD

**Issue by sammynilla** [gsomix/ChocolateyPackages#3]
By any chance would it be possible to get an update on the RenderDoc package up the latest version?

**Comment by gsomix** [comment]
@sammynilla Hey! Sure, sorry, I just completely forgot to update it. Do you by a chance, want to make a PR?

**Comment by sammynilla** [comment]
@gsomix Yep! I actually just was figuring out what I needed to do for the package itself, but I'll make a PR here in a moment.

Edit: The PR is up at #4 and hopefully that's all that'll be needed. 😄

**Comment by gsomix** [comment]
OK, I've pushed it to chocolatey, so it would be listed soon. Thank you!

https://community.chocolatey.org/packages/renderdoc/1.17
